
name: 'bank_churn_retention'
version: '1.0.0'

profile: 'bank_churn_retention'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"


models:
  +materialized: view

seeds:
  bank_churn_retention:
    Bank_Churn_Customer_Info:
      +column_types:
        EstimatedSalary: varchar
    Bank_Churn_Account_Info:
      +column_types:
        Balance: varchar

